### ISSUE TITLE
revision codigo p5_perfecto

### ISSUE THREAD

**Issue by guillemontecinos** [montoyamoraga/perfecto#1]
El código me parece bien. Tiene sentido, está clarito y bien comentado, lo leí sin ejecutar nada.
Por qué dos cámaras tiene asignado un mismo ip y la otra no?

**Comment by montoyamoraga** [comment]
porque acá donde lo probé solo tenía acceso a un iphone y a un imac, no tenía tres dispositivos,
entonces dupliqué uno, ojo cuando reemplaces la ip no borres el http de antes ni el /live de después
