### ISSUE TITLE
Apuntes ensayo Perfecto, 09/08/2017

### ISSUE THREAD

**Issue by guillemontecinos** [montoyamoraga/perfecto#2]
La aplicación se instaló en el mac de María José, v0.0.1.
Solicitaron algunas modificaciones como escala de grises y que el cursor no apareciera en la pantalla. Para ello creé una versión auxiliar v0.0.1_gray. Sugiero crear nueva versión v0.0.2 que contenga estas modificaciones y los demás cambios.
La aplicación respondió super bien y resultó cómoda y entendible para los usuarios.
Las siguientes sugerencias fueron planteadas por el equipo, las prioritarias fueron solicitadas para el próximo miércoles, las no prioritarias son para el gam:

Prioritario:
1. Color blanco y negro / sacar cursor: esto lo hice sobre la marcha en el ensayo usando <code>filter(GRAY);</code> y <code>noCursor();</code>. Guardé una versión perfecto_v001_gray.pde en el pc de María José. Implementar en versión v002.
2. Cuando el celular cambia de posición vertical/horizontal la imagen se deforma. Debemos encontrar una fórmula que evite esta deformación.
3. Poder controlar cambio de cámara en el celular frontal/selfie desde el computador. Buscar función que controle selección de cámara para implementar desde teclado.
4. Al detener la transmisión con comando “m” forzar pantalla a negro para que no quede última imagen congelada.

No Prioritario:
4. Poder controlar zoom desde el teclado del computador.

**Comment by montoyamoraga** [comment]
bacanes los apuntes, voy a poner cada problema en un issue distinto, para poder ir dejando solo las pendientes abiertas
