### ISSUE TITLE
start, restart and freeze controls

### ISSUE THREAD

**Issue by montoyamoraga** [montoyamoraga/perfecto#6]
figure out the correct sequence of pressing "m" and "n" to restart camera transmissio

**Comment by guillemontecinos** [comment]
Respecto a reseteo y reconección de las cámaras usando los comandos "m" y "n":
- Hice pruebas presionando m y n alternadamente muchas veces y el funcionamiento no sufrió problemas. Siempre se reconectó después de presionar n.
- Hice pruebas presionando muchas veces m para desconectar. Cada vez que hice esto la conexión se rehabilitó sin problemas una vez presionado el comando n.
- Probé desconectando el celular de la red wifi local y también saliendo de la app (en el iphone). En todas estas pruebas, la conexión volvió sin problemas al presionar el comando n.

**Comment by montoyamoraga** [comment]
@guillemontecinos  entonces estamos bien y fue un problema raro, revisa mañana si se cae de nuevo y toma nota si se cae, cómo pasa.
